### ISSUE TITLE
Few requests 

### ISSUE THREAD

**Issue by rgocal** [florent37/AwesomeBar#2]
This is by far one of the coolest toolbars ive ever seen for android howevor their are a few things id like to see in the near future since i have begun to use this library. 

Home icon as clickable action
Ability add overflow menu beside action item
Home icon as a icon spinner menu for switching different fragments? 
Add a menu similar to this toolbar concept http://codepen.io/OfficialAntarctica/pen/QdbZjy

Again, stupendous work!

**Comment by florent37** [comment]
I added the overflow menu and a back button ;)
